# Generated by Django 3.0.5 on 2021-11-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20211117_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
